version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.1

commands:
  set-continued-config:
    parameters:
      pipeline-parameters-json-file:
        type: string
        default: /tmp/pipeline-parameters.json
      configuration-path:
        type: string
        default: .circleci/continue.yml
      lookup-key:
        type: string
        description: key to look up the filepath for the next config
    steps:
      - run:
          name: Set next config as << parameters.configuration-path >>
          command: |
            cp $(jq -r '.<< parameters.lookup-key >>' << parameters.pipeline-parameters-json-file >>) << parameters.configuration-path >>
            # debug: confirm next config
            cat << parameters.configuration-path >>
      - run:
          name: Pop << parameters.lookup-key >> key from << parameters.pipeline-parameters-json-file >>
          command: |
            jq 'del(.<< parameters.lookup-key >>)' << parameters.pipeline-parameters-json-file >> > params.json
            rm << parameters.pipeline-parameters-json-file >>
            cp params.json << parameters.pipeline-parameters-json-file >>
            # debug: confirm contents
            jq '.' << parameters.pipeline-parameters-json-file >>


jobs:
  filter-configuration:
    executor: path-filtering/default
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: master
          mapping: |
            .* config ".circleci/no-op.yml"
            deploy/.* config ".circleci/continue-config.yml"
            deploy/.* run-deploy true
            src/.* config ".circleci/continue-config.yml"
            src/.* run-build-code true
            tests/.* config ".circleci/continue-config.yml"
            tests/.* run-tests true
      - set-continued-config:
          lookup-key: config
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json
  test-job:
    executor: path-filtering/default
    steps:
      - checkout
      - run:
          name: check parameters
          command: |
            echo "{\"run-build-code\": true}" >> /tmp/pipeline-parameters.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json


workflows:
  setup:
    jobs:
      - filter-configuration:
          filters:
            branches:
              ignore: master
      - test-job:
          filters:
            branches:
              only: master
