version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          key: scoop-{{ .Branch }}
      - run:
          name: "Install scoop and KiCad"
          command: |
            irm get.scoop.sh -outfile 'install.ps1'
            .\install.ps1 -RunAsAdmin -ScoopDir 'C:\scoop'
            scoop bucket add extras
            scoop install kicad
            scoop update kicad
      - save_cache:
          key: scoop-{{ .Branch }}
          paths:
            - C:\scoop
      - run:
          command: |
            python -m venv .env
            source .env/bin/activate
            pip install -r requirements.txt
            pwd
            ls /c/scoop/apps/kicad
          shell: bash.exe

workflows:
  my-workflow:
    jobs:
      - build
