version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps: &example-steps
      - checkout
      - run:
          name: Build
          command: echo "test"
  build2:
    docker:
      - image: cimg/node:19.7.0
    steps: &example-steps
      - checkout
      - run:
          name: Build
          command: echo "test"
      - run:
          shell: /bin/bash
          name: Build
          command: echooooo
  dependent-job:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: ./patch-status.sh
  waiter:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: ./.circleci/wait-for-jobs.sh

workflows:
  my-workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
      - waiter
      - dependent-job:
          requires:
            - waiter
