version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop bucket add extras
          scoop install kicad
      - run: |
          python -m venv .env
          venv\Scripts\Activate.ps1
          pip install -r requirements.txt
      - run:
         command: |
           echo hello
           pwd
           cd ~
           pwd
           ls -alh
           ls scoop\aapps\kicad
         shell: bash.exe

workflows:
  my-workflow:
    jobs:
      - build
