version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps: &example-steps
      - checkout
      - run:
          name: Build
          command: echo "test"
  build2:
    docker:
      - image: cimg/node:19.7.0
    steps: &example-steps
      - checkout
      - run:
          name: Build
          command: echo "test"
      - run:
          shell: /bin/bash
          name: Build
          command: echooooo
  dependent-job:
    docker: 
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: ./patch-status.sh
  waiter:
    docker: 
      - image: circleci/node
    steps:
      - run: |
          while [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job" --header "Circle-Token: $CCI_TOKEN"| jq -r '.items[]|select(.name != "waiter")|.status' | grep -c "running") -gt 0 ]]
            do
              sleep 10
            done
      - run: echo "All required jobs have now completed"

workflows:
  my-workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
      - waiter
      - dependent-job:
          requires:
            - waiter
