version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: "Run ok"
          command: |
            echo "ok"

workflows:
  my-workflow:
    jobs:
      - build
