version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          key: scoop-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Install scoop and KiCad"
          command: |
            irm get.scoop.sh -outfile 'install.ps1'
            .\install.ps1 -RunAsAdmin -ScoopDir 'C:\scoop'
            scoop bucket add extras
            scoop install kicad
            scoop update kicad
      - run:
          name: "Install dependencies"
          command: |
            .\.circleci\use-kicad-python.ps1
            python -m pip install --upgrade pip
            pip --version
            pip install -r requirements.txt
      - save_cache:
          key: scoop-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - C:\scoop
      - run:
          name: "Download kicad-kbplacer"
          command: |
            $url = "https://github.com/adamws/kicad-kbplacer/releases/download/v0.3/kicad-kbplacer.zip"
            $destination = "$env:USERPROFILE/.local/share/kicad/6.0/3rdparty/plugins"
            if(!(Test-Path $destination))
            {
                New-Item -Path $destination -ItemType Directory -Force
            }
            $tmp = "$env:TEMP"
            Invoke-WebRequest -Uri $url -OutFile "$tmp/kicad-kbplacer.zip"
            Expand-Archive -Path "$tmp/kicad-kbplacer.zip" -DestinationPath $tmp -Force
            Move-Item -Path "$tmp/plugins" -Destination $destination/com_github_adamws_kicad-kbplacer
      - run:
          name: "Run tests"
          command: |
            .\.circleci\use-kicad-python.ps1
            git clone https://github.com/adamws/kicad-kbplacer.git
            cd kicad-kbplacer/tests
            pytest --test-plugin-installation

workflows:
  my-workflow:
    jobs:
      - build
