version: 2.1

jobs:
  create-pcm-package:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              echo "Building development package"
            else
              echo "Building release package"
              echo "export KBPLACER_KICAD_STATUS=stable" >> $BASH_ENV
              echo "export KBPLACER_KICAD_RELEASE_URL=https://github.com/adamws/kicad-kbplacer/releases/download/v{version}/{zip_name}" >> $BASH_ENV
            fi
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y gettext
            python -m pip install --upgrade hatch
      - run:
          name: Create zip package and repository
          environment:
            HATCH_BUILD_HOOK_ENABLE_KICAD-REPOSITORY: true
          command: |
            python -m hatch build --target kicad-package
      - store_artifacts:
          path: dist/repository
      - persist_to_workspace:
          root: .
          paths:
            - dist/repository/*
      - when: # run only on master
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "d0:4f:c2:dd:e2:fe:9c:25:33:57:3e:fd:09:bd:9e:5c"
            - run:
                name: Deploy repository to github pages
                command: |
                  ./release/deploy.sh
  create-pypi-package:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install hatch==1.7.0
      - run:
          name: Create distribution archive
          command: |
            python -m hatch -v build -t sdist
      - run:
          name: Sanity check result package
          command: |
            python -m venv .env
            . .env/bin/activate
            pip install dist/kbplacer*.tar.gz
            python -c 'from kbplacer.kle_serial import parse_kle; print(parse_kle([["",""]]))'
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist/kbplacer*.tar.gz
  create-github-release:
    docker:
      - image: cimg/base:2023.12
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install dependencies
          command: |
            ./release/install_gh.sh
      - run:
          name: Create draft release
          command: |
            if [ -z "$CIRCLE_TAG" ]; then exit 1; fi
            gh config set prompt disabled
            gh release create $CIRCLE_TAG --draft --verify-tag --title $CIRCLE_TAG
      - run:
          name: Upload artifacts to release
          command: |
            NAME=kbplacer-$(echo $CIRCLE_TAG | cut -c 2-)
            gh release upload $CIRCLE_TAG \
              /tmp/workspace/dist/$NAME.tar.gz \
              /tmp/workspace/dist/repository/$NAME.zip \
              /tmp/workspace/dist/repository/packages.json \
              /tmp/workspace/dist/repository/repository.json \
              /tmp/workspace/dist/repository/resources.zip

workflows:
  kicad-release:
    jobs:
      - create-pcm-package:
          filters: &tag-filter
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - create-pypi-package:
          filters: *tag-filter
      - create-github-release:
          filters: *tag-filter
          requires:
            - create-pcm-package
            - create-pypi-package
