version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.1


jobs:
  filter-configuration:
    executor: path-filtering/default
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: master
          mapping: |
            deploy/.* run-deploy true
            src/.* run-build-code true
            tests/.* run-tests true
      - run:
          name: Print continuation parameters
          command: |
            cat /tmp/pipeline-parameters.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json
  test-job:
    executor: path-filtering/default
    steps:
      - checkout
      - run:
          name: check parameters
          command: |
            echo "{\"run-build-code\": true}" >> /tmp/pipeline-parameters.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json


workflows:
  setup:
    jobs:
      - filter-configuration:
          filters:
            branches:
              only: master
      - test-job:
          filters:
            branches:
              ignore: master
