version: 2.1

parameters:
  run-build-code:
    type: boolean
    default: false
  run-deploy:
    type: boolean
    default: false
  run-tests:
    type: boolean
    default: false

jobs:
  build-test-deploy:
    docker:
      - image: cimg/base:2022.09
    steps:
      - run:
          name: Build and test
          command: echo "build-test"
      - run:
          name: Debug
          command: echo << pipeline.git.branch >>
      - when: # run only on master when code or deployment scripts changed, do not run when only tests changed:
          condition:
            and:
              - or:
                - << pipeline.git.tag >>
                - equal: [ master, << pipeline.git.branch >> ]
              - or: [ << pipeline.parameters.run-build-code >>, << pipeline.parameters.run-deploy >> ]
          steps:
            - run:
                name: Deploy
                command: echo "deploy"

workflows:
  build-test-deploy:
    when:
      or:
        - << pipeline.parameters.run-build-code >>
        - << pipeline.parameters.run-tests >>
        - << pipeline.parameters.run-deploy >>
    jobs:
      - build-test-deploy:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
