name: Build

on:
  push:
  pull_request:

jobs:

  build-and-test-cyrus-sasl:
    name: Build and test cyrus-sasl
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'adamws/conan-center-index'
          ref: 'cyrus-sasl-msvc-test'
      - run: python -m pip install conan
      - shell: bash
        run: |
          cd recipes/cyrus-sasl/all
          conan profile detect
          conan create . --version 2.1.28 --build=missing --options cyrus-sasl/*:shared=True

  build-and-test-cyrus-sasl2:
    name: Build and test cyrus-sasl2
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'adamws/conan-center-index'
          ref: 'cyrus-sasl-allow-to-disable-saslauthd'
      - run: python -m pip install conan
      - shell: bash
        run: |
          cd recipes/cyrus-sasl/all
          conan profile detect
          conan create . --version 2.1.28 --build=missing --options cyrus-sasl/*:shared=True

  build-and-test-rxspencer:
    name: Build and test rxspencer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'adamws/conan-center-index'
          ref: 'rxspencer'
      - run: python -m pip install conan
      - shell: bash
        run: |
          cd recipes/rxspencer/all
          conan profile detect
          conan create . --version 3.9.0
